### ISSUE TITLE
Can't log-in? :(

### ISSUE THREAD

**Issue by hdrdavies** [CoffeeDotFilter/retweetr#31]
I was totes looking forward to that as well 

![image](https://cloud.githubusercontent.com/assets/13098199/13699940/9c056c30-e775-11e5-8d89-c8433e18132b.png)

**Comment by hdrdavies** [comment]
It's working now :)

**Comment by sofer** [comment]
@hdrdavies not for me.

**Comment by oturnermajor** [comment]
Should be OK now (#40)
