### ISSUE TITLE
Code spacing

### ISSUE THREAD

**Issue by hdrdavies** [CoffeeDotFilter/retweetr#32]
[This file](https://github.com/CoffeeDotFilter/retweetr/blob/47ae135fd8221c4bedcaf27010a0063d1e6f3806/public/style.css)...

could be a bit more readable with the code alignment. Also consider indenting css selectors that are within other selectors. I found it made it much more intuitive to read when you come back to it. e.g. [here](https://github.com/dwyl/dwyl.github.io/blob/14e4ceb478353826ede3baba822fbd8d16616edc/css/dwyl.css#L47).

Love the file structure though guys! Very tidy and logical.

**Comment by andrewMacmurray** [comment]
@hdrdavies that's really interesting, never thought of doing that!

**Comment by hdrdavies** [comment]
@andrewMacmurray Makes it a bit more like HTML / JS nesting
