### ISSUE TITLE
Nice code in server.js ! 

### ISSUE THREAD

**Issue by hdrdavies** [CoffeeDotFilter/retweetr#33]
[Wow!](https://github.com/CoffeeDotFilter/retweetr/blob/47ae135fd8221c4bedcaf27010a0063d1e6f3806/lib/server.js)

Really like the way you've separated out the handlebars views config. I've never thought of doing that before so will do that next time. Also nice use of arrays to supply the plugins / routes. 

:+1:

**Comment by andrewMacmurray** [comment]
@hdrdavies thanks :smile: it definitely helped us with navigating our files

**Comment by hdrdavies** [comment]
@andrewMacmurray yeah! I find that Hapi is really great for that. I love the plugin-style architecture.

**Comment by Jbarget** [comment]
:+1:
