### ISSUE TITLE
Replication of tweets

### ISSUE THREAD

**Issue by hdrdavies** [CoffeeDotFilter/retweetr#36]
After about 5 tweets, there was some replication of tweets. Try to have new ones rolling out or the user might get confused :+1:

**Comment by oturnermajor** [comment]
Not sure what would have caused this - possibly you were clicking one of the buttons which resulted in the page refreshing and getting the same tweets again. Otherwise you should be able to swipe through 50 (different) tweets. 

If it was the buttons, then #44 should have fixed this.
