### ISSUE TITLE
No user feedback on using the heart button

### ISSUE THREAD

**Issue by hdrdavies** [CoffeeDotFilter/retweetr#37]
When you press the button (not sliding), there's no feedback that anything has happened- it just refreshes the page. I really like the feedback for the sliding option - the big red screen with 'FAVOURITED' - could you do the same for the button?

**Comment by oturnermajor** [comment]
Yeahhhh this is a stretch goal. At the moment those buttons are just cosmetic. They don't actually favourite or retweet the tweet that you're on.

**Comment by hdrdavies** [comment]
Oh really. In that case, maybe the page shouldn't refresh? Because it suggests it's doing something....

**Comment by oturnermajor** [comment]
Stretch goal achieved! Got the buttons working with #44, and they should work on Heroku as well.

Bin icon skips tweet, settings icon logs you out.

**Comment by hdrdavies** [comment]
@oturnermajor Great! I would say that a settings icon suggests that you'd be able to adjust settings, rather than just logging out.... Maybe an arrow to a door type icon, like this? 

![logout](http://uxrepo.com/static/icon-sets/ionicons/svg/log-out.svg)
