### ISSUE TITLE
Positive feedback

### ISSUE THREAD

**Issue by hdrdavies** [CoffeeDotFilter/retweetr#38]
I know I've opened a fair amount of issues here - sorry about that. I hope you realise I'm trying to help :wink: This project is really great though guys! Especially since there's 3 of you as well. I think the readme is **excellent**, the file structure is *really, really* good, and you've got a bunch of functionality in there with a couple of great little add ons - auth & sliders. 

### Great jobs guys!

**Comment by andrewMacmurray** [comment]
@hdrdavies :heart: thanks Huw, glad you like

**Comment by oturnermajor** [comment]
:) Yayyyy
